version: "3"
services:
  app:
    build: .
    ports:
      - "8000:5000"
    container_name: app_flask_firebase
    volumes:
      - ./app:/usr/src/app
    command: flask run --host=0.0.0.0 --debugger --reload